/**
 * Chat API SDK
 * The SDK allows you to receive and send messages through your WhatsApp account. [Sign up now](https://app.chat-api.com/)  The Chat API is based on the WhatsApp WEB protocol and excludes the ban both when using libraries from mgp25 and the like. Despite this, your account can be banned by anti-spam system WhatsApp after several clicking the \"block\" button.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: sale@chat-api.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import SetWebhookStatus from '../Queen-Lora/SetWebhookStatus';
import WebhookUrl from '../Queen-Lora/WebhookUrl';

/**
* Class4Webhooks service.
* @module api/Class4WebhooksApi
* @version 1.0.0
*/
export default class Class4WebhooksApi {

    /**
    * Constructs a new Class4WebhooksApi. 
    * @alias module:api/Class4WebhooksApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }



    /**
     * Sets the URL for receiving webhook
     * Sets the URL for receiving webhook notifications of new messages and message delivery events (ack).  **API responses in \"Callbacks\" tab**
     * @param {module:Queen-Lora/WebhookUrl} webhookUrl 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:Queen-Lora/SetWebhookStatus} and HTTP response
     */
    setWebhookWithHttpInfo(webhookUrl) {
      let postBody = webhookUrl;
      // verify the required parameter 'webhookUrl' is set
      if (webhookUrl === undefined || webhookUrl === null) {
        throw new Error("Missing the required parameter 'webhookUrl' when calling setWebhook");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['instanceId', 'token'];
      let contentTypes = ['application/x-www-form-urlencoded', 'application/json'];
      let accepts = ['application/json'];
      let returnType = SetWebhookStatus;
      return this.apiClient.callApi(
        '/webhook', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Sets the URL for receiving webhook
     * Sets the URL for receiving webhook notifications of new messages and message delivery events (ack).  **API responses in \"Callbacks\" tab**
     * @param {module:Queen-Lora/WebhookUrl} webhookUrl 
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:Queen-Lora/SetWebhookStatus}
     */
    setWebhook(webhookUrl) {
      return this.setWebhookWithHttpInfo(webhookUrl)
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


}
