/**
 * Chat API SDK
 * The SDK allows you to receive and send messages through your WhatsApp account. [Sign up now](https://app.chat-api.com/)  The Chat API is based on the WhatsApp WEB protocol and excludes the ban both when using libraries from mgp25 and the like. Despite this, your account can be banned by anti-spam system WhatsApp after several clicking the \"block\" button.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: sale@chat-api.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Ack model module.
 * @module Queen-Lora/Ack
 * @version 1.0.0
 */
class Ack {
    /**
     * Constructs a new <code>Ack</code>.
     * @alias module:Queen-Lora/Ack
     */
    constructor() { 
        
        Ack.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>Ack</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:Queen-Lora/Ack} obj Optional instance to populate.
     * @return {module:Queen-Lora/Ack} The populated <code>Ack</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Ack();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('queueNumber')) {
                obj['queueNumber'] = ApiClient.convertToType(data['queueNumber'], 'Number');
            }
            if (data.hasOwnProperty('chatId')) {
                obj['chatId'] = ApiClient.convertToType(data['chatId'], 'String');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
        }
        return obj;
    }

/**
     * Returns unique id
     * @return {String}
     */
    getId() {
        return this.id;
    }

    /**
     * Sets unique id
     * @param {String} id unique id
     */
    setId(id) {
        this['id'] = id;
    }
/**
     * Returns message id in queue
     * @return {Number}
     */
    getQueueNumber() {
        return this.queueNumber;
    }

    /**
     * Sets message id in queue
     * @param {Number} queueNumber message id in queue
     */
    setQueueNumber(queueNumber) {
        this['queueNumber'] = queueNumber;
    }
/**
     * Returns chat ID
     * @return {String}
     */
    getChatId() {
        return this.chatId;
    }

    /**
     * Sets chat ID
     * @param {String} chatId chat ID
     */
    setChatId(chatId) {
        this['chatId'] = chatId;
    }
/**
     * Returns type of the message status
     * @return {module:Queen-Lora/Ack.StatusEnum}
     */
    getStatus() {
        return this.status;
    }

    /**
     * Sets type of the message status
     * @param {module:Queen-Lora/Ack.StatusEnum} status type of the message status
     */
    setStatus(status) {
        this['status'] = status;
    }

}

/**
 * unique id
 * @member {String} id
 */
Ack.prototype['id'] = undefined;

/**
 * message id in queue
 * @member {Number} queueNumber
 */
Ack.prototype['queueNumber'] = undefined;

/**
 * chat ID
 * @member {String} chatId
 */
Ack.prototype['chatId'] = undefined;

/**
 * type of the message status
 * @member {module:Queen-Lora/Ack.StatusEnum} status
 */
Ack.prototype['status'] = undefined;





/**
 * Allowed values for the <code>status</code> property.
 * @enum {String}
 * @readonly
 */
Ack['StatusEnum'] = {

    /**
     * value: "delivered"
     * @const
     */
    "delivered": "delivered",

    /**
     * value: "viewed"
     * @const
     */
    "viewed": "viewed"
};



export default Ack;

