/**
 * Chat API SDK
 * The SDK allows you to receive and send messages through your WhatsApp account. [Sign up now](https://app.chat-api.com/)  The Chat API is based on the WhatsApp WEB protocol and excludes the ban both when using libraries from mgp25 and the like. Despite this, your account can be banned by anti-spam system WhatsApp after several clicking the \"block\" button.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: sale@chat-api.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The GroupParticipantStatus model module.
 * @module Queen-Lora/GroupParticipantStatus
 * @version 1.0.0
 */
class GroupParticipantStatus {
    /**
     * Constructs a new <code>GroupParticipantStatus</code>.
     * @alias module:Queen-Lora/GroupParticipantStatus
     */
    constructor() { 
        
        GroupParticipantStatus.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>GroupParticipantStatus</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:Queen-Lora/GroupParticipantStatus} obj Optional instance to populate.
     * @return {module:Queen-Lora/GroupParticipantStatus} The populated <code>GroupParticipantStatus</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GroupParticipantStatus();

            if (data.hasOwnProperty('add')) {
                obj['add'] = ApiClient.convertToType(data['add'], 'Boolean');
            }
            if (data.hasOwnProperty('message')) {
                obj['message'] = ApiClient.convertToType(data['message'], 'String');
            }
            if (data.hasOwnProperty('groupId')) {
                obj['groupId'] = ApiClient.convertToType(data['groupId'], 'String');
            }
        }
        return obj;
    }

/**
     * @return {Boolean}
     */
    getAdd() {
        return this.add;
    }

    /**
     * @param {Boolean} add
     */
    setAdd(add) {
        this['add'] = add;
    }
/**
     * Returns Status of adding participant to group
     * @return {String}
     */
    getMessage() {
        return this.message;
    }

    /**
     * Sets Status of adding participant to group
     * @param {String} message Status of adding participant to group
     */
    setMessage(message) {
        this['message'] = message;
    }
/**
     * @return {String}
     */
    getGroupId() {
        return this.groupId;
    }

    /**
     * @param {String} groupId
     */
    setGroupId(groupId) {
        this['groupId'] = groupId;
    }

}

/**
 * @member {Boolean} add
 */
GroupParticipantStatus.prototype['add'] = undefined;

/**
 * Status of adding participant to group
 * @member {String} message
 */
GroupParticipantStatus.prototype['message'] = undefined;

/**
 * @member {String} groupId
 */
GroupParticipantStatus.prototype['groupId'] = undefined;






export default GroupParticipantStatus;

