/**
 * Chat API SDK
 * The SDK allows you to receive and send messages through your WhatsApp account. [Sign up now](https://app.chat-api.com/)  The Chat API is based on the WhatsApp WEB protocol and excludes the ban both when using libraries from mgp25 and the like. Despite this, your account can be banned by anti-spam system WhatsApp after several clicking the \"block\" button.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: sale@chat-api.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import OutboundAction from './OutboundAction';

/**
 * The OutboundActions model module.
 * @module Queen-Lora/OutboundActions
 * @version 1.0.0
 */
class OutboundActions {
    /**
     * Constructs a new <code>OutboundActions</code>.
     * @alias module:Queen-Lora/OutboundActions
     */
    constructor() { 
        
        OutboundActions.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>OutboundActions</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:Queen-Lora/OutboundActions} obj Optional instance to populate.
     * @return {module:Queen-Lora/OutboundActions} The populated <code>OutboundActions</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new OutboundActions();

            if (data.hasOwnProperty('totalActions')) {
                obj['totalActions'] = ApiClient.convertToType(data['totalActions'], 'Number');
            }
            if (data.hasOwnProperty('first100')) {
                obj['first100'] = ApiClient.convertToType(data['first100'], [OutboundAction]);
            }
        }
        return obj;
    }

/**
     * Returns Total number of actions in the queue
     * @return {Number}
     */
    getTotalActions() {
        return this.totalActions;
    }

    /**
     * Sets Total number of actions in the queue
     * @param {Number} totalActions Total number of actions in the queue
     */
    setTotalActions(totalActions) {
        this['totalActions'] = totalActions;
    }
/**
     * @return {Array.<module:Queen-Lora/OutboundAction>}
     */
    getFirst100() {
        return this.first100;
    }

    /**
     * @param {Array.<module:Queen-Lora/OutboundAction>} first100
     */
    setFirst100(first100) {
        this['first100'] = first100;
    }

}

/**
 * Total number of actions in the queue
 * @member {Number} totalActions
 */
OutboundActions.prototype['totalActions'] = undefined;

/**
 * @member {Array.<module:Queen-Lora/OutboundAction>} first100
 */
OutboundActions.prototype['first100'] = undefined;






export default OutboundActions;

