/**
 * Chat API SDK
 * The SDK allows you to receive and send messages through your WhatsApp account. [Sign up now](https://app.chat-api.com/)  The Chat API is based on the WhatsApp WEB protocol and excludes the ban both when using libraries from mgp25 and the like. Despite this, your account can be banned by anti-spam system WhatsApp after several clicking the \"block\" button.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: sale@chat-api.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import Ack from './Queen-Lora/Ack';
import BanSettings from './Queen-Lora/BanSettings';
import BanTestAction from './Queen-Lora/BanTestAction';
import BanTestStatus from './Queen-Lora/BanTestStatus';
import Chat from './Queen-Lora/Chat';
import ChatIdProp from './Queen-Lora/ChatIdProp';
import ChatUpdate from './Queen-Lora/ChatUpdate';
import Chats from './Queen-Lora/Chats';
import ClearActionsQueueStatus from './Queen-Lora/ClearActionsQueueStatus';
import ClearMessagesQueueStatus from './Queen-Lora/ClearMessagesQueueStatus';
import CreateGroupAction from './Queen-Lora/CreateGroupAction';
import CreateGroupStatus from './Queen-Lora/CreateGroupStatus';
import ForwardMessageRequest from './Queen-Lora/ForwardMessageRequest';
import GroupParticipantAction from './Queen-Lora/GroupParticipantAction';
import GroupParticipantStatus from './Queen-Lora/GroupParticipantStatus';
import InlineResponse200 from './Queen-Lora/InlineResponse200';
import InlineResponse2001 from './Queen-Lora/InlineResponse2001';
import InlineResponse2002 from './Queen-Lora/InlineResponse2002';
import InlineResponse2003 from './Queen-Lora/InlineResponse2003';
import InlineResponse2004 from './Queen-Lora/InlineResponse2004';
import InlineResponse2005 from './Queen-Lora/InlineResponse2005';
import InlineResponse2005Update from './Queen-Lora/InlineResponse2005Update';
import InlineResponse401 from './Queen-Lora/InlineResponse401';
import InstanceStatus from './Queen-Lora/InstanceStatus';
import InstanceStatusAction from './Queen-Lora/InstanceStatusAction';
import InstanceStatusLink from './Queen-Lora/InstanceStatusLink';
import InstanceStatusStatusData from './Queen-Lora/InstanceStatusStatusData';
import InstanceStatusStatusDataActions from './Queen-Lora/InstanceStatusStatusDataActions';
import Message from './Queen-Lora/Message';
import Messages from './Queen-Lora/Messages';
import OutboundAction from './Queen-Lora/OutboundAction';
import OutboundActions from './Queen-Lora/OutboundActions';
import OutboundMessage from './Queen-Lora/OutboundMessage';
import OutboundMessages from './Queen-Lora/OutboundMessages';
import PhoneProp from './Queen-Lora/PhoneProp';
import ReadChatAction from './Queen-Lora/ReadChatAction';
import ReadChatStatus from './Queen-Lora/ReadChatStatus';
import SendContactRequest from './Queen-Lora/SendContactRequest';
import SendFileRequest from './Queen-Lora/SendFileRequest';
import SendLinkRequest from './Queen-Lora/SendLinkRequest';
import SendLocationRequest from './Queen-Lora/SendLocationRequest';
import SendMessageRequest from './Queen-Lora/SendMessageRequest';
import SendMessageStatus from './Queen-Lora/SendMessageStatus';
import SendPTTRequest from './Queen-Lora/SendPTTRequest';
import SendVCardRequest from './Queen-Lora/SendVCardRequest';
import SetWebhookStatus from './Queen-Lora/SetWebhookStatus';
import Settings from './Queen-Lora/Settings';
import Status from './Queen-Lora/Status';
import Statuses from './Queen-Lora/Statuses';
import WebhookStatus from './Queen-Lora/WebhookStatus';
import WebhookUrl from './Queen-Lora/WebhookUrl';
import Class1InstanceApi from './api/Class1InstanceApi';
import Class2MessagesApi from './api/Class2MessagesApi';
import Class3ChatsApi from './api/Class3ChatsApi';
import Class4WebhooksApi from './api/Class4WebhooksApi';
import Class5QueuesApi from './api/Class5QueuesApi';
import Class6BanApi from './api/Class6BanApi';
import Class7TestingApi from './api/Class7TestingApi';


/**
* The_SDK_allows_you_to_receive_and_send_messages_through_your_WhatsApp_account___Sign_up_now_https__app_chat_api_com_The_Chat_API_is_based_on_the_WhatsApp_WEB_protocol_and_excludes_the_banboth_when_using_libraries_from_mgp25_and_the_like__Despite_this_youraccount_can_be_banned_by_anti_spam_system_WhatsApp_after_several_clickingthe_block_button_.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var Node = require('index'); // See note below*.
* var xxxSvc = new Node.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new Node.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new Node.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new Node.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 1.0.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The Ack model constructor.
     * @property {module:Queen-Lora/Ack}
     */
    Ack,

    /**
     * The BanSettings model constructor.
     * @property {module:Queen-Lora/BanSettings}
     */
    BanSettings,

    /**
     * The BanTestAction model constructor.
     * @property {module:Queen-Lora/BanTestAction}
     */
    BanTestAction,

    /**
     * The BanTestStatus model constructor.
     * @property {module:Queen-Lora/BanTestStatus}
     */
    BanTestStatus,

    /**
     * The Chat model constructor.
     * @property {module:Queen-Lora/Chat}
     */
    Chat,

    /**
     * The ChatIdProp model constructor.
     * @property {module:Queen-Lora/ChatIdProp}
     */
    ChatIdProp,

    /**
     * The ChatUpdate model constructor.
     * @property {module:Queen-Lora/ChatUpdate}
     */
    ChatUpdate,

    /**
     * The Chats model constructor.
     * @property {module:Queen-Lora/Chats}
     */
    Chats,

    /**
     * The ClearActionsQueueStatus model constructor.
     * @property {module:Queen-Lora/ClearActionsQueueStatus}
     */
    ClearActionsQueueStatus,

    /**
     * The ClearMessagesQueueStatus model constructor.
     * @property {module:Queen-Lora/ClearMessagesQueueStatus}
     */
    ClearMessagesQueueStatus,

    /**
     * The CreateGroupAction model constructor.
     * @property {module:Queen-Lora/CreateGroupAction}
     */
    CreateGroupAction,

    /**
     * The CreateGroupStatus model constructor.
     * @property {module:Queen-Lora/CreateGroupStatus}
     */
    CreateGroupStatus,

    /**
     * The ForwardMessageRequest model constructor.
     * @property {module:Queen-Lora/ForwardMessageRequest}
     */
    ForwardMessageRequest,

    /**
     * The GroupParticipantAction model constructor.
     * @property {module:Queen-Lora/GroupParticipantAction}
     */
    GroupParticipantAction,

    /**
     * The GroupParticipantStatus model constructor.
     * @property {module:Queen-Lora/GroupParticipantStatus}
     */
    GroupParticipantStatus,

    /**
     * The InlineResponse200 model constructor.
     * @property {module:Queen-Lora/InlineResponse200}
     */
    InlineResponse200,

    /**
     * The InlineResponse2001 model constructor.
     * @property {module:Queen-Lora/InlineResponse2001}
     */
    InlineResponse2001,

    /**
     * The InlineResponse2002 model constructor.
     * @property {module:Queen-Lora/InlineResponse2002}
     */
    InlineResponse2002,

    /**
     * The InlineResponse2003 model constructor.
     * @property {module:Queen-Lora/InlineResponse2003}
     */
    InlineResponse2003,

    /**
     * The InlineResponse2004 model constructor.
     * @property {module:Queen-Lora/InlineResponse2004}
     */
    InlineResponse2004,

    /**
     * The InlineResponse2005 model constructor.
     * @property {module:Queen-Lora/InlineResponse2005}
     */
    InlineResponse2005,

    /**
     * The InlineResponse2005Update model constructor.
     * @property {module:Queen-Lora/InlineResponse2005Update}
     */
    InlineResponse2005Update,

    /**
     * The InlineResponse401 model constructor.
     * @property {module:Queen-Lora/InlineResponse401}
     */
    InlineResponse401,

    /**
     * The InstanceStatus model constructor.
     * @property {module:Queen-Lora/InstanceStatus}
     */
    InstanceStatus,

    /**
     * The InstanceStatusAction model constructor.
     * @property {module:Queen-Lora/InstanceStatusAction}
     */
    InstanceStatusAction,

    /**
     * The InstanceStatusLink model constructor.
     * @property {module:Queen-Lora/InstanceStatusLink}
     */
    InstanceStatusLink,

    /**
     * The InstanceStatusStatusData model constructor.
     * @property {module:Queen-Lora/InstanceStatusStatusData}
     */
    InstanceStatusStatusData,

    /**
     * The InstanceStatusStatusDataActions model constructor.
     * @property {module:Queen-Lora/InstanceStatusStatusDataActions}
     */
    InstanceStatusStatusDataActions,

    /**
     * The Message model constructor.
     * @property {module:Queen-Lora/Message}
     */
    Message,

    /**
     * The Messages model constructor.
     * @property {module:Queen-Lora/Messages}
     */
    Messages,

    /**
     * The OutboundAction model constructor.
     * @property {module:Queen-Lora/OutboundAction}
     */
    OutboundAction,

    /**
     * The OutboundActions model constructor.
     * @property {module:Queen-Lora/OutboundActions}
     */
    OutboundActions,

    /**
     * The OutboundMessage model constructor.
     * @property {module:Queen-Lora/OutboundMessage}
     */
    OutboundMessage,

    /**
     * The OutboundMessages model constructor.
     * @property {module:Queen-Lora/OutboundMessages}
     */
    OutboundMessages,

    /**
     * The PhoneProp model constructor.
     * @property {module:Queen-Lora/PhoneProp}
     */
    PhoneProp,

    /**
     * The ReadChatAction model constructor.
     * @property {module:Queen-Lora/ReadChatAction}
     */
    ReadChatAction,

    /**
     * The ReadChatStatus model constructor.
     * @property {module:Queen-Lora/ReadChatStatus}
     */
    ReadChatStatus,

    /**
     * The SendContactRequest model constructor.
     * @property {module:Queen-Lora/SendContactRequest}
     */
    SendContactRequest,

    /**
     * The SendFileRequest model constructor.
     * @property {module:Queen-Lora/SendFileRequest}
     */
    SendFileRequest,

    /**
     * The SendLinkRequest model constructor.
     * @property {module:Queen-Lora/SendLinkRequest}
     */
    SendLinkRequest,

    /**
     * The SendLocationRequest model constructor.
     * @property {module:Queen-Lora/SendLocationRequest}
     */
    SendLocationRequest,

    /**
     * The SendMessageRequest model constructor.
     * @property {module:Queen-Lora/SendMessageRequest}
     */
    SendMessageRequest,

    /**
     * The SendMessageStatus model constructor.
     * @property {module:Queen-Lora/SendMessageStatus}
     */
    SendMessageStatus,

    /**
     * The SendPTTRequest model constructor.
     * @property {module:Queen-Lora/SendPTTRequest}
     */
    SendPTTRequest,

    /**
     * The SendVCardRequest model constructor.
     * @property {module:Queen-Lora/SendVCardRequest}
     */
    SendVCardRequest,

    /**
     * The SetWebhookStatus model constructor.
     * @property {module:Queen-Lora/SetWebhookStatus}
     */
    SetWebhookStatus,

    /**
     * The Settings model constructor.
     * @property {module:Queen-Lora/Settings}
     */
    Settings,

    /**
     * The Status model constructor.
     * @property {module:Queen-Lora/Status}
     */
    Status,

    /**
     * The Statuses model constructor.
     * @property {module:Queen-Lora/Statuses}
     */
    Statuses,

    /**
     * The WebhookStatus model constructor.
     * @property {module:Queen-Lora/WebhookStatus}
     */
    WebhookStatus,

    /**
     * The WebhookUrl model constructor.
     * @property {module:Queen-Lora/WebhookUrl}
     */
    WebhookUrl,

    /**
    * The Class1InstanceApi service constructor.
    * @property {module:api/Class1InstanceApi}
    */
    Class1InstanceApi,

    /**
    * The Class2MessagesApi service constructor.
    * @property {module:api/Class2MessagesApi}
    */
    Class2MessagesApi,

    /**
    * The Class3ChatsApi service constructor.
    * @property {module:api/Class3ChatsApi}
    */
    Class3ChatsApi,

    /**
    * The Class4WebhooksApi service constructor.
    * @property {module:api/Class4WebhooksApi}
    */
    Class4WebhooksApi,

    /**
    * The Class5QueuesApi service constructor.
    * @property {module:api/Class5QueuesApi}
    */
    Class5QueuesApi,

    /**
    * The Class6BanApi service constructor.
    * @property {module:api/Class6BanApi}
    */
    Class6BanApi,

    /**
    * The Class7TestingApi service constructor.
    * @property {module:api/Class7TestingApi}
    */
    Class7TestingApi
};
