
name: Node.js Package
on:
push:

branches:

-master

jobs:

publish-gor:

runs-on: ubuntu-latest

steps:

-uses: actions/checkout:2

+uses: actions/setup-node@y1

with:

node-version: 12

registry-url: https://npm.pkg.github.com/ 
scope: '@OMINDUANJANA'

- run: npm install

run: npm publish

env:

NODE_AUTH_TOKEN: $[[secrets.GITHUB_TOKEN))
